- hosts: all
  gather_facts: false
  tasks:
  - include_role:
      role: network_backup_restore
    vars:
      action: backup
  - include_role:
      role: network_backup_restore
    vars:
      action: restore
  - debug:
      var: last_backup
