- name: Get a timestamp
  set_fact:
    current_date_ts: "{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"
  delegate_to: localhost
  run_once: True

- name: Creates backup directory
  file:
    path: "{{ backup_directory }}"
    state: directory
  delegate_to: localhost
  run_once: True
